name: Python Tests

# Ce workflow s'exécute sur les événements suivants :
on:
  push:
    branches:
      - main       # Exécute sur chaque push vers la branche `main`
  pull_request:
    branches:
      - main       # Exécute sur chaque pull request vers `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu pour exécuter les tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone le code de votre repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Utilise Python 3.8, vous pouvez changer la version selon vos besoins

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances spécifiées dans requirements.txt

    - name: Run tests with pytest
      run: |
        pytest  # Exécute les tests dans le répertoire `tests/` avec pytest

