name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances

    - name: Add Source to PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/Source:$PYTHONPATH" >> $GITHUB_ENV  # Ajoute Source au PYTHONPATH

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Exécute les tests avec pytest
